
<form id="bo-payment-info-form" action="">
<fieldset>
    <ul class="form-list">

                <li class="wide">
                    <div class="input-box">
                        <label for="paymentInfo"><?php echo nl2br($this->helper('buyback')->getPaymentInfoTitle()) ?></label>
                        <textarea id="paymentInfo" title="Payment Info" name="payment_info"  class="input-text" ></textarea>
                    </div>
                </li>
    </ul>
        <div class="buttons-set" id="billing-buttons-container">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="billing.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span class="please-wait" id="billing-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
        </div>
</fieldset>

</form>
<script type="text/javascript">
//<![CDATA[
var billing = new Billing('bo-payment-info-form', '<?php echo $this->getUrl('buyback/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('buyback/onepage/savePaymentInfo') ?>');

    var billingForm = new VarienForm('bo-payment-info-form');
//]]>
</script>
