
                <div class="cat-section1">
                    <div class="row">
                        <div class="inline-horizental">
                            <div class="label-text">
                                <h1>Véndenos tu</h1>
                            </div>
                            <div class="input-group">
                                <div class="select-group">
                                    <span id="select6" class="select16">celulr</span>
   
                                   <select class="styled16" name="6" onchange="javascript:document.getElementById('select6').innerHTML=this.value;">
                                       <option>celulr</option>
                                        <option>celulr2</option>
                                   </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <ul class="category-list">
                            <li>
                                <div class="pro-logo"><img src="<?php echo $this->getSkinUrl(''); ?>images/iphone-logo.png" alt=""/></div>
                                <div class="pro-image">
                                    <a href="#"><img src="<?php echo $this->getSkinUrl(''); ?>images/i-phone.jpg" alt=""/></a>
                                </div>
                                <div class="pro-name">
                                   <a href="#"> Quiero vender mi iPhone</a>
                                </div>
                            </li>
                            <li>
                                <div class="pro-logo"><img src="<?php echo $this->getSkinUrl(''); ?>images/android.png" alt=""/></div>
                                <div class="pro-image">
                                    <a href="#"><img src="<?php echo $this->getSkinUrl(''); ?>images/i-phone2.png" alt=""/></a>
                                </div>
                                <div class="pro-name">
                                   <a href="#"> Quiero vender mi Android</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                
                <div class="home-section2">
                    <div class="gft-section2">
                        <div class="title">
                            <h1>Compra aquí tu <br/>próximo celular y tablet</h1>
                        </div>
                        <div class="row">
                            <div class="gft-left">
                                <p>Todos nuestros equipos son verificados por nuestro equipo técnico altamente calificado y cumplen nuestra certificación GADFY de calidad, asegurandote un equipo funcional y en buen estado.</p>
                            
                                </div>
                             <div class="gft-right"> <img src="<?php echo $this->getSkinUrl(''); ?>images/gadfi-logo.png" alt=""/></div>
                        </div>                        
                    </div>
                    <button class="button yellow-btn large-block">
                        <span>
                            <span>Equipos disponibles</span>
                        </span>
                    </button>
                </div>
                
                <div class="home-section2 customer-block">
                    <div class="padd">
                        <div class="row">
                            <div class="block-post-title">
                                <h1>Conoce que dicen</h1>
                                <h2>NUESTROS CLIENTES</h2>
                            </div>
                            <div class="block-des">
                                <sup>“</sup>Pude vender mi celular en 30 min de forma confiable y rapida. ¡Que buen servicio!
                            </div>
                             <div class="block-post">
                                <div class="block-mem-name">
                                    <p>Ricardo Gómez</p>
                                    <p>Vendi mi iPhone 5 - 32GB</p>
                                </div>
                                <div class="post-image">
                                    <img src="<?php echo $this->getSkinUrl(''); ?>images/post-img.png" alt=""/>
                                </div>
                             </div>
                        </div>
                        <button class="button green-btn large-block">
                            <span>
                                <span>Más historias de clientes satisfechos</span>
                            </span>
                        </button>
                        
                    </div>
                </div>
                
                 <div class="home-section2">
                    <div class="gdfy-funciona-container">
                    <div class="title center">
                        <h1>¿Cómo funciona GADFY?</h1>
                    </div>
                    <div class="gdfy-funciona">
                        <ul>
                            <li class="gdfy-bg1">
                                <div class="dp-table">
                                    <div class="dp-table-con">
                                        <div class="number-text">1.</div>
                                        <div class="funci-des">Cotiza tu celular otablet</div>
                                    </div>
                                    <button class="button green-btn large-block"><span><span>Quiero cotizar mi equipo ya</span> </span></button>
                                </div>
                            </li>
                            <li class="gdfy-bg2">
                                <div class="dp-table">
                                    <div class="dp-table-con">
                                        <div class="number-text">2.</div>
                                        <div class="funci-des"><p>Si estas de acuerdo con tu oferta, solicita la recolección gratis</p></div>
                                    </div>
                                </div>
                            </li>
                            <li class="gdfy-bg3">
                                <div class="dp-table">
                                    <div class="dp-table-con">
                                        <div class="number-text">3.</div>
                                        <div class="funci-des">Recolectamos tu equipo</div>
                                    </div>
                                </div>
                            </li>
                            <li class="gdfy-bg4">
                                <div class="dp-table">
                                    <div class="dp-table-con">
                                        <div class="number-text">4.</div>
                                        <div class="funci-des">Si el equipo está como nos dijiste, recibe lo acordado</div>
                                    </div>                                    
                                </div>
                            </li>                           
                        </ul>
                        <a class="button yellow-btn gadfy-video"><span class="icon">video</span>Mira como funciona GADFY</a>
                    </div>
                    </div>
                 </div>
                

